FROM continuumio/miniconda3

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt

RUN pip install numpy

# RUN conda install numpy pandas

ENTRYPOINT ["python"]

